# Generated by Django 4.1 on 2022-08-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='review',
        ),
    ]
